# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSO2Lp6FbcJMqeB83lKS-bMqAVqiqTUS
"""

# Importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load datasets
data1 = pd.read_csv('/content/dataset_tk.csv')
data2 = pd.read_csv('/content/long_data_.csv')

# Rename columns for clarity
data1.rename(columns={'Unnamed: 0': 'Date'}, inplace=True)
data2.rename(columns={'Dates': 'Date'}, inplace=True)

# Convert date columns to datetime format
data1['Date'] = pd.to_datetime(data1['Date'], errors='coerce')
data2['Date'] = pd.to_datetime(data2['Date'], errors='coerce')

# Drop duplicates from data2
data2.drop_duplicates(inplace=True)

# Plotting the total power usage across different states in dataset 1
plt.figure(figsize=(15, 7))
for state in data1.columns[1:]:
    plt.plot(data1['Date'], data1[state], label=state)
plt.title('Power Consumption Over Time by State')
plt.xlabel('Date')
plt.ylabel('Power Consumption')
plt.legend(loc='upper right', ncol=2, fontsize='small')
plt.show()

# Grouping data by region to get total power consumption
region_usage = data2.groupby('Regions')['Usage'].sum().sort_values()

# Plotting regional power consumption
plt.figure(figsize=(10, 6))
sns.barplot(x=region_usage.index, y=region_usage.values)
plt.title('Total Power Consumption by Region')
plt.xlabel('Region')
plt.ylabel('Total Power Usage')
plt.xticks(rotation=45)
plt.show()

# Grouping data by region to get total power consumption
region_usage = data2.groupby('Regions')['Usage'].sum().sort_values()

# Plotting regional power consumption
plt.figure(figsize=(10, 6))
sns.barplot(x=region_usage.index, y=region_usage.values)
plt.title('Total Power Consumption by Region')
plt.xlabel('Region')
plt.ylabel('Total Power Usage')
plt.xticks(rotation=45)
plt.show()

# Save cleaned data to new CSV files
data1.to_csv('/content/py/cleaned_dataset_tk.csv', index=False)
data2.to_csv('/content/py/cleaned_long_data.csv', index=False)